import { writable } from "svelte/store";

export const white = writable(false)
export const showFilter = writable(false)

export const listForTicker: ArrayLike<string> = [
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists',
]

export const items = [
    {
        title: 'WHAT BOTHERS ME',
        mainImg: 'https://picsum.photos/500/500',
        images: [],
        video: 'https://www.youtube.com/watch?v=_9mf8Qhcank',
        tagNames: ['видео', 'женскийстайлинг', 'мужскойстайлинг'],
        tags: ['видео', 'женский', 'мужской'],
        classes: 'p-5',
    },
    { title: 'BAIKAL', video: '', mainImg: '/images/projects/baikal/1.jpg', images: ['/images/projects/baikal/1.jpg', '/images/projects/baikal/2.jpg', '/images/projects/baikal/3.jpg', '/images/projects/baikal/4.jpg', '/images/projects/baikal/5.jpg',], tags: ['фото', 'реклама', 'женский', 'мужской'], tagNames: ['фото', 'реклама', 'женскийстайлинг', 'мужскойстайлинг'] },
    {
        title: 'SPIN4SPIN',
        mainImg: '/images/projects/spin/11.jpg',
        images: [
            '/images/projects/spin/1.jpg',
            '/images/projects/spin/2.jpg',
            '/images/projects/spin/3.jpg',
            '/images/projects/spin/4.jpg',
            '/images/projects/spin/5.jpg',
            '/images/projects/spin/6.jpg',
            '/images/projects/spin/7.jpg',
            '/images/projects/spin/8.jpg',
            '/images/projects/spin/9.jpg',
            '/images/projects/spin/10.jpg',
            '/images/projects/spin/11.jpg',
            '/images/projects/spin/12.jpg',
        ],
        tags: ['фото', 'фешн', 'женский', 'мужской'],
        tagNames: ['фото', 'фешн', 'женскийстайлинг', 'мужскойстайлинг'],
        classes: 'px-5',
    },
];