import { writable } from "svelte/store";

export const white = writable(false)
export const showFilter = writable(true)

export const topActive = writable(false)
export const botActive = writable(false)

export const lvl1All = writable(false);
export const lvl2All = writable(false);
export const lvl3All = writable(false);
export const lvl1 = writable([]);
export const lvl2 = writable([]);
export const lvl3 = writable([]);

export const listForTicker: ArrayLike<string> = [
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists |',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
    'costumes designers |',
    'fashion stylists',
]
